server:
  port: 8899
logging:
  level:
    root: INFO
spring:
  redis:
    redisson:
      file: classpath:redisson.yml
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    servlet:
      multipart:
        maxFileSize: -1
        maxRequestSize: -1
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
    mvc:
      static-path-pattern: /**
      pathmatch:
        matching-strategy: ant_path_matcher
#忽略权限拦截，外部系统，例如springboot admin 和mq刷新配置都需要权限
management:
  endpoints:
    web:
      exposure:
        #开放所有页面节点  默认只开启了health、info两个节点，注意yml的*要使用双引号
        include: "*"
  endpoint:
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: ALWAYS
swagger:
  basePackage: com.redisson
  gitUrl: http://192.168.0.89/gac-nev-monitor-center/nev-monitor-center.git
